<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>TurnTabler</AssemblyName>
    <Version>2.1.0</Version>
    <ApplicationIcon>Assets/Icon/TurnTabler.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <StartupObject>TurnTabler.Program</StartupObject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4191.47" />
    <EmbeddedResource Include="../ui/assets/glass-turntable.png" LogicalName="TurnTabler.Assets.Record.png" />
    <EmbeddedResource Include="YouTubeBridge.js" LogicalName="TurnTabler.Assets.YouTubeBridge.js" />
    <EmbeddedResource Include="Assets/Icon/TurnTabler.ico" LogicalName="TurnTabler.Assets.App.ico" />
  </ItemGroup>
</Project>
